model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: claude-3-5-haiku-latest
    litellm_params:
      model: anthropic/claude-3-5-haiku-latest
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: ollama/llama3
    litellm_params:
      model: ollama/llama3
      api_base: http://host.docker.internal:11434

litellm_settings:
  drop_params: true
  set_verbose: false
  forward_headers_to_metadata: true
  success_callback: ["langfuse", "usejunction_callback.usejunction_logger"]
  failure_callback: ["langfuse", "usejunction_callback.usejunction_logger"]
  callbacks:
    - usejunction_callback.usejunction_logger

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

router_settings:
  enable_pre_call_checks: true
